CUAHANGBANSACH/Controllers/QLNXBController.cs
using CUAHANGBANSACH.Models.DAO;
using CUAHANGBANSACH.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace CUAHANGBANSACH.Controllers
{
    public class QLNXBController : Controller
    {
        public bool KiemTraPhanQuyen(string cv)
        {
            NHANVIEN nv = (NHANVIEN)Session["NhanVien"];
            var check = NHANVIEN_DAO.KiemTraPhanQuyen(nv.manhanvien, cv);
            if (check != null) return true;
            return false;
        }
        // GET: QLNXB
        public ActionResult Index(string Find)
        {
            if (!KiemTraPhanQuyen("CV02"))
                return View("Bạn không có quyền truy cập vào page");
            if (TempData["Result"] != null)
            {
                if (TempData["Result"].ToString().Contains("Successful")) ViewBag.Success = TempData["Result"];
                else ViewBag.Failure = TempData["Result"];
            }
            
            if (Find != null) return PartialView(NXB_DAO.GetByName(Find));
            return View(NXB_DAO.GetList());
        }

        public ActionResult Detail(string MaNXB)
        {
            if (!KiemTraPhanQuyen("CV02"))
                return View("Bạn không có quyền truy cập vào page");

            var ttnxb = NXB_DAO.GetById(MaNXB);
            if (ttnxb != null) return View(ttnxb);
            return View("Can't Find");
        }
        public ActionResult Create ()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(NXB model)
        {
            if (!KiemTraPhanQuyen("CV02"))
                return View("Bạn không có quyền truy cập vào page");

            var ttnxb = NXB_DAO.GetById(model.manxb);
            if (ttnxb != null)
            {
                ModelState.AddModelError("manxb", "Thông tin nxb có tồn tại trong CSDL");
                return View(model);
            }

            NXB nxb = new NXB()
            {
                manxb = model.manxb,
                tennxb = model.tennxb,
            };

            try
            {
                NXB_DAO.Create(nxb);
                TempData["Result"] = "Add Book Information Successful";
                return RedirectToAction("Index");

            } catch
            {
                return View("Có lỗi xảy ra khi thêm");
            }
            
        }

        public ActionResult Edit(string MaNXB)
        {
            if (!KiemTraPhanQuyen("CV02"))
                return View("Bạn không có quyền truy cập vào page");

            var ttnxb = NXB_DAO.GetById(MaNXB);
            if (ttnxb != null) return View(ttnxb);
            return View("Can't Find");
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit (NXB model)
        {
            if (!KiemTraPhanQuyen("CV02"))
                return View("Bạn không có quyền truy cập vào page");

            var ttnxb = NXB_DAO.GetById(model.manxb);
            if (ttnxb != null)
            {
                ttnxb.tennxb = model.tennxb;

                try
                {
                    NXB_DAO.Update(model);
                    TempData["Result"] = "Update NXB Information Successful";
                    return RedirectToAction("Index");


                } catch
                {
                    TempData["Result"] = "Update NXB Information Failure";
                    return View("Có lỗi xảy ra khi cập nhật");
                }
            }
            return View("Can't Find");
        }
        public ActionResult Delete(string MaNXB)
        {
            if (!KiemTraPhanQuyen("CV02"))
                return View("Bạn không có quyền truy cập vào page");
            var ttnxb = NXB_DAO.GetById(MaNXB);
            if (ttnxb != null) return View(ttnxb);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(NXB model)
        {
            if (!KiemTraPhanQuyen("CV02"))
                return View("Bạn không có quyền truy cập vào page");
            var ttnxb = NXB_DAO.GetById(model.manxb);
            if (ttnxb == null) return View("Không tìm thấy");

            List<SACH> sach = new List<SACH>();
            sach = SACH_DAO.GetByNXBId(model.manxb);
            if (sach != null)
            {
                foreach (SACH hon in sach)
                {
                    hon.manxb = "0";

                    try
                    {
                        SACH_DAO.Update(hon);
                    }
                    catch
                    {
                        return View("Error");
                    }
                }
                
            }
            try
            {
                NXB_DAO.Delete(model);
                TempData["Result"] = "Delete NXB Successful";
                return RedirectToAction("Index");

            }
            catch (Exception ex) { }
            {
                ModelState.AddModelError("error", "Lỗi xóa NXB");
                TempData["Result"] = "Delete NXB Failure";
                return View(model);
            }
        }
    }
}

CUAHANGBANSACH/Views/QLNXB/Create.cshtml
@model CUAHANGBANSACH.Models.NXB

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout_Staff.cshtml";
}

<section id="content">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Thêm NXB</h4>
                        <hr class="colorgraph"/>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.manxb, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.manxb, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.manxb, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.tennxb, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.tennxb, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.tennxb, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }

                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>
            </div>
        </div>
    </div>
</section>




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CUAHANGBANSACH/Views/QLNXB/Delete.cshtml
@model CUAHANGBANSACH.Models.NXB

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout_Staff.cshtml";
}

<section id="content">


    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>NXB</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.tennxb)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.tennxb)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                
            </div>
        }
    </div>
</section>

CUAHANGBANSACH/Views/QLNXB/Detail.cshtml
@model CUAHANGBANSACH.Models.NXB

@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout_Staff.cshtml";
}

<section id="content">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <h4>Nhà Xuất Bản @Model.tennxb</h4>
                <hr class="container"/>
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.tennxb)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.tennxb)
                    </dd>

                </dl>
            </div>
            <div class="form-graph">
                <p>
                    <input type="button" value="Cập nhật thông tin thể loại" onclick="location.href='@Url.Action("Update", "QLNXB", routeValues: new { @MaNXB = Model.manxb })'" />
                    <input type="button" value="Trở lại danh sách" onclick="location.href='@Url.Action("Index", "QLNXB")'" />
                </p>
            </div>
        </div>
    </div>
</section>

CUAHANGBANSACH/Views/QLNXB/Edit.cshtml
@model CUAHANGBANSACH.Models.NXB

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout_Staff.cshtml";
}

<section id="content">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Cập Nhật Thông Tin NXB @Model.manxb</h4>
                        <hr class="colorgraph"/>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.manxb)

                        <div class="form-group">
                            @Html.LabelFor(model => model.tennxb, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.tennxb, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.tennxb, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Save" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }

                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>
            </div>
        </div>
    </div>
</section>




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CUAHANGBANSACH/Views/QLNXB/Index.cshtml
@model IEnumerable<CUAHANGBANSACH.Models.NXB>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_Staff.cshtml";
}


@if (Model == null)
{
    <h2>Danh sách rỗng</h2>
}
else
{
    <section id="content">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>DANH SÁCH NHÀ XUẤT BẢN</h2>
                    <hr class="colorgraph" />


                    <div class="col-lg-4" style="margin-top:10px; margin-bottom: 10px">
                        <input type="button" style="color: white; background-color:green;" value="Add new TL" onclick="location.href='@Url.Action("Create", "QLNXB")'" />

                    </div>

                    <div class="col-lg-8" style="margin-top:10px; margin-bottom: 10px">
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()
                            <div class="col-lg-6">

                                @Html.Editor("Find", "", new { htmlAttributes = new { @class = "form-control input-lg", @placeholder = "Nhập tên nhà xuất bản cần tìm" } })

                            </div>
                            <div class="col-lg-2">
                                <input type="submit" value="Tìm kiếm" class="btn btn-default" />
                            </div>
                        }
                    </div>

                    <div class="card mb-12">
                        <div class="card-body">
                            @if (ViewBag.Success != null)
                            {
                                <div id="msgAlert" class="alert alert-success" role="alert">
                                    @ViewBag.Success
                                </div>
                            }
                            else if (ViewBag.Failure != null)
                            {
                                <div id="msgAlert" class="alert alert-danger" role="alert">
                                    @ViewBag.Failure
                                </div>

                            }
                        </div>
                    </div>
                    <table class="table">
                        <tr>
                            <th>
                                Mã NXB
                            </th>
                            <th>
                                Tên NXB
                            </th>

                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.manxb) </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.tennxb)
                                </td>
                                <td>
                                    <input type="button" style="color: white; background-color:darkblue;" value="Edit" onclick="location.href='@Url.Action("Edit", "QLNXB", routeValues: new { @MaNXB = item.manxb })'" />
                                    <input type="button" style="color: white; background-color: red;" value="Thông tin nhà xuất bản" onclick="location.href='@Url.Action("Detail", "QLNXB", routeValues: new { @MaNXB = item.manxb })'" />
                                    <input type="button" style="color: white; background-color: grey;" value="Xóa NXB" onclick="location.href='@Url.Action("Delete", "QLNXB", routeValues: new { @MaNXB = item.manxb })'" />

                                </td>
                            </tr>
                        }

                    </table>
                </div>
            </div>
        </div>

    </section>
}