CUAHANGBANSACH/Controllers/QLTLController.cs
using CUAHANGBANSACH.Models.DAO;
using CUAHANGBANSACH.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CUAHANGBANSACH.Controllers
{
    public class QLTLController : Controller
    {
        // GET: QLTL
        public bool KiemTraPhanQuyen(string cv)
        {
            NHANVIEN nv = (NHANVIEN)Session["NhanVien"];
            var check = NHANVIEN_DAO.KiemTraPhanQuyen(nv.manhanvien, cv);
            if (check != null) return true;
            return false;
        }
        public ActionResult Index(string Find)
        {
            if (!KiemTraPhanQuyen("CV02"))
            return View("Bạn không có quyền truy cập vào page");
            //viet code lay danh sach o day (Tạo GetAllList ở THELOAI_DAO)
            if (TempData["Result"] != null)
            {
                if (TempData["Result"].ToString().Contains("Successful")) ViewBag.Success = TempData["Result"];
                else ViewBag.Failure = TempData["Result"];
            }

            if (Find != null)
            {
                return View(THELOAI_DAO.GetName(Find));
            }
            return View(THELOAI_DAO.GetList());
        }

        public ActionResult Create()
        {
            if (!KiemTraPhanQuyen("CV02"))
                return View("Bạn không có quyền truy cập vào page");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(THELOAISACH model)
        {
            if (!KiemTraPhanQuyen("CV02"))
                return View("Bạn không có quyền truy cập vào page");

            var getbyid = THELOAI_DAO.GetbyId(model.matheloai);
            if (getbyid != null)
            {
                return View("Không thêm được!!!");
            }
            try
            {
                THELOAISACH tls = new THELOAISACH() { matheloai = model.matheloai, tentheloai = model.tentheloai };
                THELOAI_DAO.create(tls);

                TempData["Result"] = "Add CATEGORY Information Successful";
                return RedirectToAction("index");
            }
            catch (Exception ex) { return View(); }

            //Code tim kiem the loai
            //Nếu mã thể loại tồn tại thì trả về tồn tại
            //Tạo thêm thể loại (nhớ tạo Create bên THELOAI_DAO)
            

            
        }
        public ActionResult Details (string MaTL) 
        {
            if (!KiemTraPhanQuyen("CV02"))
                return View("Bạn không có quyền truy cập vào page");

            //code lấy thông tin thể loại
            var tttl = THELOAI_DAO.GetbyId(MaTL);
            if (tttl != null) return View(tttl);
            return View("Không có tìm thấy"); 
        }

        public ActionResult Update(string MaTL) 
        {
            if (!KiemTraPhanQuyen("CV02"))
                return View("Bạn không có quyền truy cập vào page");
            var tttl = THELOAI_DAO.GetbyId(MaTL);
            if (tttl != null) return View(tttl);
            return View("Không có tìm thấy");
            //code lấy thông tin thể loại
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(THELOAISACH model)
        {
            if (!KiemTraPhanQuyen("CV02"))
                return View("Bạn không có quyền truy cập vào page");
            var getbyid = THELOAI_DAO.GetbyId(model.matheloai);
            if (getbyid != null)
            {
                getbyid.tentheloai = model.tentheloai;
                try
                {
                    THELOAI_DAO.update(getbyid);
                    TempData["Result"] = "Update CATEGORY Information Successful";
                    return RedirectToAction("index");
                }
                catch (Exception ex) { return View("Error"); }
            } return View("Error");

            //update tên thể loại (Tạo Update tại DAO)
            
        }

        public ActionResult Delete(string MaTL) 
        {
            if (!KiemTraPhanQuyen("CV02"))
                return View("Bạn không có quyền truy cập vào page");

            var tttl = THELOAI_DAO.GetbyId(MaTL);
            if (tttl != null) return View(tttl);
            return View("Không có tìm thấy");
            
        
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(THELOAISACH model)
        {
            if (!KiemTraPhanQuyen("CV02"))
                return View("Bạn không có quyền truy cập vào page");

            var tttl = THELOAI_DAO.GetbyId(model.matheloai);
            if (tttl == null) return View("Không tìm thấy");
            
            List<SACH> sach = new List<SACH>();
            sach = SACH_DAO.GetByNXBId(model.matheloai);
            if (sach != null)
            {
                foreach (SACH hon in sach)
                {
                    hon.matheloai = "0";

                    try
                    {
                        SACH_DAO.Update(hon);
                    }
                    catch
                    {
                        return View("Error");
                    }
                }

            }
            try
            {
                THELOAI_DAO.delete(model);
                TempData["Result"] = "Delete CATEGORY Successful";
                return RedirectToAction("Index");

            }
            catch (Exception ex) { }
            {
                ModelState.AddModelError("error", "Lỗi xóa NXB");
                TempData["Result"] = "Delete NXB Failure";
                return View(model);
            }
            

        }

    }
}

CUAHANGBANSACH/Views/QLTL/Create.cshtml
@model CUAHANGBANSACH.Models.THELOAISACH

@{
    ViewBag.Title = "Create";
}



<section id="content">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Thêm thể loại sách</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.matheloai, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.matheloai, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.matheloai, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.tentheloai, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.tentheloai, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.tentheloai, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }

                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>
            </div>
        </div>
    </div>
</section>

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }

CUAHANGBANSACH/Views/QLTL/Delete.cshtml
@model CUAHANGBANSACH.Models.THELOAISACH

@{
    ViewBag.Title = "Delete";
}


<section id="content">


    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>THELOAISACH</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.tentheloai)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.tentheloai)
            </dd>

        </dl>

        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                
            </div>
        }
    </div>
    </section>

CUAHANGBANSACH/Views/QLTL/Details.cshtml
@model CUAHANGBANSACH.Models.THELOAISACH

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout_Staff.cshtml";
}


<section id="content">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <h4>Thông tin thể loại @Model.tentheloai</h4>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.tentheloai)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.tentheloai)
                    </dd>

                </dl>
            </div>
            <div class="form-graph">
                <p>
                    <input type="button" value="Cập nhật thông tin thể loại" onclick="location.href='@Url.Action("Update", "QLTL", routeValues: new { @MaTL = Model.matheloai })'" />
                    <input type="button" value="Trở lại danh sách" onclick="location.href='@Url.Action("Index", "QLTL")'" />
                </p>
            </div>
        </div>
    </div>
</section>

CUAHANGBANSACH/Views/QLTL/Index.cshtml
@model IEnumerable<CUAHANGBANSACH.Models.THELOAISACH>

@{
    ViewBag.Title = "Index";
}

<section id="content">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2>DANH SÁCH SÁCH</h2>
                <hr class="colorgraph" />

                <p>
                    @Html.ActionLink("Create New", "Create")
                </p>
                <table class="table">
                    <tr>
                        <th>
                            Mã Thể Loại
                        </th>
                        <th>
                            Tên thể loại
                        </th>
                        
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.matheloai) </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.tentheloai)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", routeValues: new { @MaTL = item.matheloai }) |
                                @Html.ActionLink("Details", "Details", routeValues: new { @MaTL = item.matheloai }) |
                                @Html.ActionLink("Delete", "Delete", routeValues: new { @MaTL = item.matheloai })
                            </td>
                        </tr>
                    }

                </table>
            </div>
        </div>
    </div>

</section>

CUAHANGBANSACH/Views/QLTL/Update.cshtml
@model CUAHANGBANSACH.Models.THELOAISACH

@{
    ViewBag.Title = "Update";
}



<section id="content">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>CẬP NHẬT THÔNG TIN THỂ LOẠI @Model.matheloai</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.matheloai)

                        <div class="form-group">
                            @Html.LabelFor(model => model.tentheloai, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.tentheloai, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.tentheloai, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Save" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }

                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>
            </div>
        </div>
    </div>
</section>

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }