CUAHANGBANSACH/Controllers/GUESTLOGINController.cs
using CUAHANGBANSACH.Models;
using CUAHANGBANSACH.Models.DAO;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using System.Web.Razor.Text;

namespace CUAHANGBANSACH.Controllers
{
    public class GUESTLOGINController : Controller
    {
        // GET: GUESTLOGIN
        
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(KHACH model)
        {
            
                KHACH kHACH = KHACH_DAO.GetByTDN(model.tendangnhap);
                if (kHACH == null)
                {
                    ModelState.AddModelError("tendangnhap", "Tên đăng nhập không tìm thấy");
                    return View(model);
                    //return Json(new { success = false, message = "Đăng nhập thất bại!" });
                }
                if (kHACH.matkhau != model.matkhau)
                {
                    ModelState.AddModelError("matkhau", "Mật Khẩu không đúng");
                    return View(model);
                    //return Json(new { success = false, message = "Đăng nhập thất bại!" });
                }
                Session["KHACH"] = kHACH;
                Session.Timeout = 240;
            //var ttdonhang = PHIEUMUAHANG_DAO.GetDHById(model.tendangnhap);
            /*if (ttdonhang == null)
            {
                Session["Đơn Hàng"] = null;
            } else
            {
                if (ttdonhang.tinhtrang == "Chưa Xác Nhận") Session["Đơn Hàng"] = ttdonhang;
                else Session["Đơn Hàng"] = null;
            }*/
            //Session["Đơn Hàng"] = "DH20240323180959";
            return RedirectToAction("Index", "Home");
            //return Json(new { success = true, message = "Đăng nhập thành công!" });
        }
            //else return View(model);
        
        public ActionResult Logout()
        {
            Session.Remove("KHACH");
            Session.Remove("Đơn Hàng");
            return RedirectToAction("Index", "Home");
        }

        public ActionResult UpdateMK()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateMK(KHACH model, string confirmPassword)
        {
            var Update = KHACH_DAO.GetByTDN(model.tendangnhap);
            if (Update != null)
            {
                if (model.matkhau != confirmPassword)
                {
                    ModelState.AddModelError("confirmPassword", "Mật khẩu nhập lại không trùng khớp");
                    return View(model);
                }
                Update.matkhau = model.matkhau;
                try
                {
                    KHACH_DAO.Update(Update);
                    return RedirectToAction("Index", "Home");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("tendangnhap", ex.Message);
                    return View(model);
                }
            }
            else if (model.matkhau == null || confirmPassword == null)
            {
                ModelState.AddModelError("matkhau", "Mật khẩu không được trống");
                return View(model);
            }
            ModelState.AddModelError("tendangnhap", "Lỗi không tìm thấy");
            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(KHACH model, HttpPostedFileBase image)
        {
            DateTime dt = new DateTime();
            var create = KHACH_DAO.GetById(model.makhachhang);
            string fileName = "";
            if (create == null)
            {
                dt = DateTime.Now;
                if (image != null && image.ContentLength > 0)
                {
                    var uploadPath = Server.MapPath("~/Content/GuestAvatar/");
                    if (!Directory.Exists(uploadPath)) Directory.CreateDirectory(uploadPath);

                    fileName = Path.GetFileName(image.FileName);
                    string filePath = Path.Combine(Server.MapPath("~/Content/GuestAvatar/"), fileName);

                    if (System.IO.File.Exists(filePath))
                    {
                        System.IO.File.Delete(filePath);
                    }

                    image.SaveAs(filePath);

                }

                KHACH khach = new KHACH()
                {
                    makhachhang = "KH" + dt.ToString("yyyyMMddHHmmss"),
                    tenkhachhang = model.tenkhachhang,
                    diachi = model.diachi,
                    sdt = model.sdt,
                    email = model.email,
                    avatar = "/Content/GuestAvatar/" + fileName,
                    tendangnhap = model.tendangnhap,
                    matkhau = model.matkhau,
                    
                };
                try
                {
                    KHACH_DAO.Create(khach);
                    return RedirectToAction("Index", "Home");

                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("tenkhachhang", "Lỗi không tạo được");
                    return View(model);
                }

            }
            ModelState.AddModelError("makhachhang", "Tài khoản đã tồn tại!");
            return View(model);
        }

        public ActionResult TTKH()
        {
            /*KHACH khach = (KHACH)Session["KHACH"];
            var tttk = KHACH_DAO.GetById(khach.makhachhang);
            if ( tttk != null)
            {
                khach = tttk;
            }*/
            return View();
        }

        public ActionResult UpdateTT(string Ma_KH)
        {
            return View(KHACH_DAO.GetById(Ma_KH));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateTT(KHACH model)
        {
            //KHACH khach = (KHACH)Session["KHACH"];
            var update = KHACH_DAO.GetById(model.makhachhang);
            if (update == null)
            {
                return HttpNotFound();
            }

            update.tenkhachhang = model.tenkhachhang;
            update.sdt = model.sdt;
            update.diachi = model.diachi;
            update.avatar = model.avatar;
            update.email = model.email;


            try
            {
                KHACH_DAO.Update(update);
                //khach = update;
                return RedirectToAction("TTKH");
            }
            catch (Exception ex)
            {
                return View("Có lỗi xảy ra", "Index");
            }

        }

        public ActionResult UploadImage(string Ma_KH)
        {
            return View(KHACH_DAO.GetById(Ma_KH));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UploadImage(KHACH model, HttpPostedFileBase image)
        {
            var idmakh = KHACH_DAO.GetById(model.makhachhang);
            if (idmakh == null) return View("Không tìm thấy");

            if (image != null && image.ContentLength > 0)
            {
                var uploadPath = Server.MapPath("~/Content/GuestAvatar/");
                if (!Directory.Exists(uploadPath)) Directory.CreateDirectory(uploadPath);

                string fileName = Path.GetFileName(image.FileName);
                string filePath = Path.Combine(Server.MapPath("~/Content/GuestAvatar/"), fileName);

                if (System.IO.File.Exists(filePath))
                {
                    System.IO.File.Delete(filePath);
                }

                image.SaveAs(filePath);
                idmakh.makhachhang = model.makhachhang;
                idmakh.avatar = "/Content/GuestAvatar/" + fileName;
                
            }
            try
            {
                KHACH_DAO.Update(idmakh);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                //ModelState.AddModelError("error", "Lỗi cập nhật thông tin");
                return View("Lỗi cập nhật thông tin");
            }
        }

        public ActionResult Delete(String Ma_KH) {
            return View(KHACH_DAO.GetById(Ma_KH));
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(KHACH model) {
            return View();
        }
    }

}

CUAHANGBANSACH/Controllers/TTKHController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CUAHANGBANSACH.Controllers
{
    public class TTKHController : Controller
    {
        // GET: TTKH
        public ActionResult Index()
        {
            return View();
        }
    }
}

CUAHANGBANSACH/Views/GUESTLOGIN/Create.cshtml
@model CUAHANGBANSACH.Models.KHACH

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
<section id="content">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
                @using (Html.BeginForm("Create", "GUESTLOGIN", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>ĐĂNG KÝ TÀI KHOẢN KHÁCH</h4>
                    <h5>Tài Khoản</h5>

                    <div class="form-group">
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.tendangnhap, new { htmlAttributes = new { @class = "form-control input-lg", @placeholder = "Tên Đăng Nhập" } })
                            @Html.ValidationMessageFor(model => model.tendangnhap, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.matkhau, new { htmlAttributes = new { @class = "form-control input-lg", @placeholder = "Mật Khẩu", type = "password" } })
                            @Html.ValidationMessageFor(model => model.matkhau, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <hr class="colorgraph" />
                    <h5>Nhập thông tin cơ bản</h5>

                    <div class="form-group">

                        <div class="col-md-10">
                            @Html.EditorFor(model => model.tenkhachhang, new { htmlAttributes = new { @class = "form-control input-lg", @placeholder = "Tên Khách Hàng" } })
                            @Html.ValidationMessageFor(model => model.tenkhachhang, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">

                        <div class="col-md-10">
                            @Html.EditorFor(model => model.diachi, new { htmlAttributes = new { @class = "form-control input-lg", @placeholder = "Địa Chỉ" } })
                            @Html.ValidationMessageFor(model => model.diachi, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">

                        <div class="col-md-10">
                            @Html.EditorFor(model => model.sdt, new { htmlAttributes = new { @class = "form-control input-lg", @placeholder = "Số Điện Thoại" } })
                            @Html.ValidationMessageFor(model => model.sdt, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">

                        <div class="col-md-10">
                            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control input-lg", @placeholder = "Email" } })
                            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">

                        <input type="file" class="form-control" name="image" />

                    </div>

                    <hr class="colorgraph" />
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </div>
                </div>
                }
            </div>
        </div>
    </div>
    

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</section>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CUAHANGBANSACH/Views/GUESTLOGIN/Delete.cshtml
@model CUAHANGBANSACH.Models.KHACH

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete your information?</h3>
<div>
    <h4>KHACH</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.tenkhachhang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tenkhachhang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.diachi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.diachi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sdt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sdt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.avatar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.avatar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tendangnhap)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tendangnhap)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.matkhau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.matkhau)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "TTKH")
        </div>
    }
</div>

CUAHANGBANSACH/Views/GUESTLOGIN/Login.cshtml
@model CUAHANGBANSACH.Models.KHACH

@{
    ViewBag.Title = "Login";
}


            <section id="content">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
                            
                            @using (Html.BeginForm("Login", "GUESTLOGIN", FormMethod.Post))
                            {
                                @Html.AntiForgeryToken()
                                <h2>Login</h2>
                                <hr class="colorgraph" />

                                <div class="form-group">
                                    @Html.TextBoxFor(m => m.tendangnhap, htmlAttributes: new { @class = "form-control input-lg", @placeholder = "Tài Khoản" }) <br />
                                    @Html.ValidationMessageFor(m => m.tendangnhap, "", new { @class = "text-danger" })
                                </div>

                                <div class="form-group">
                                    @Html.TextBoxFor(m => m.matkhau, htmlAttributes: new { @class = "form-control input-lg", @placeholder = "Mật Khẩu", type = "password" })
                                    <br />
                                    @Html.ValidationMessageFor(m => m.matkhau, "", new { @class = "text-danger" })
                                </div>

                                <hr class="colorgraph" />
                                <div class="row">
                                    <div class="col-xs-12 col-md-6">
                                        <input id="LoginForm" type="submit" value="Đăng Nhập" class="btn btn-primary btn-block" />
                                    </div>

                                    <div class="col-xs-12 col-md-6">
                                        <p>@Html.ActionLink("Đổi Mật Khẩu", "UpdateMK", "GUESTLOGIN", new { area = "" }, new { @class = "nav-link" })</p>

                                    </div>
                                    <div class="col-xs-12 col-md-6">
                                        <p>@Html.ActionLink("Đăng Ký Tài Khoản", "Create", "GUESTLOGIN", new { area = "" }, new { @class = "nav-link" })</p>
                                    </div>
                                </div>

                                //@Html.ValidationSummary()

                                @ViewBag.Status
                            }
                        </div>
                    </div>
                </div>


            </section>

CUAHANGBANSACH/Views/GUESTLOGIN/TTKH.cshtml
@{
    ViewBag.Title = "TTKH";
    
    KHACH khach = (KHACH)Session["KHACH"];
    
}

<section id="content">
    <div class="container">
        <div class="row">
            <h2>Chi tiết thông tin Khách @khach.tenkhachhang </h2>
            <hr class="colorgraph" />
            <div class="col-lg-4">
                <h3>Ảnh đại diện</h3>
                <div class="form-group">
                    @if (!string.IsNullOrEmpty(khach.avatar))
                    {
                        <img src=@khach.avatar style="width: 200px; height: auto;" />
                    }
                    else
                    {
                        <span>Không có ảnh</span>
                    }


                </div>
                <div class="form-group">
                    <input type="button" value="Upload Ảnh" onclick="location.href='@Url.Action("UploadImage", "GUESTLOGIN", routeValues: new { @Ma_KH = khach.makhachhang })'" />

                </div>


            </div>

            <dl class="col-lg-8">
                <dt>
                    @Html.DisplayNameFor(model => khach.tenkhachhang)
                </dt>

                <dd>
                    @Html.DisplayFor(model => khach.tenkhachhang)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => khach.diachi)
                </dt>

                <dd>
                    @Html.DisplayFor(model => khach.diachi)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => khach.sdt)
                </dt>

                <dd>
                    @Html.DisplayFor(model => khach.sdt)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => khach.email)
                </dt>

                <dd>
                    @Html.DisplayFor(model => khach.email)
                </dd>

            </dl>
        </div>
        <div class="form-group">
            <input type="button" value="Cập nhật thông tin khách" onclick="location.href='@Url.Action("UpdateTT", "GUESTLOGIN", routeValues: new { @Ma_KH = khach.makhachhang })'" />
            <input type="button" value="Thông tin thẻ" onclick="location.href='@Url.Action("Index", "THE", routeValues: new { @Ma_KH = khach.makhachhang })'" />
            
        </div>

    </div>

</section>

CUAHANGBANSACH/Views/GUESTLOGIN/UpdateMK.cshtml
@model CUAHANGBANSACH.Models.KHACH

@{
    ViewBag.Title = "UpdateMK";
}

<h2>UpdateMK</h2>

<section id="content">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
                @using (Html.BeginForm("UpdateMK", "GUESTLOGIN", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Đổi Mật Khẩu Tài Khoản Khách</h4>
                        <hr class="colorgraph" />

                        <div class="form-group">
                            
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.tendangnhap, new { htmlAttributes = new { @class = "form-control input-lg", @placeholder="Tên Đăng Nhập" } })
                                @Html.HiddenFor(model => model.tendangnhap)
                                @Html.ValidationMessageFor(model => model.tendangnhap, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.matkhau, new { htmlAttributes = new { @class = "form-control input-lg", @placeholder = "Mật Khẩu", type="password" } })
                                @Html.ValidationMessageFor(model => model.matkhau, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            
                            <div class="col-md-10">

                                @Html.EditorFor(model => model.confirmPassword, new { htmlAttributes = new { @class = "form-control input-lg", @placeholder = "Mật Khẩu Nhập Lại", type="password" } })
                                @Html.ValidationMessageFor(model => model.confirmPassword, "", new { @class = "text-danger" })

                            </div>
                        </div>
                        <hr class="colorgraph"/>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Save" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    


</section>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CUAHANGBANSACH/Views/GUESTLOGIN/UpdateTT.cshtml
@model CUAHANGBANSACH.Models.KHACH

@{
    ViewBag.Title = "UpdateTT";
}


<section id="content">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                <div class="form-horizontal">

                    
                    @Html.HiddenFor(model => model.makhachhang)

                    <h4>CẬP NHẬT THÔNG TIN</h4>
                    <hr class="colorgraph"/>

                    <div class="form-group">
                        
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.tenkhachhang, new { htmlAttributes = new { @class = "form-control input-lg", @placeholder="Tên Khách Hàng" } })
                            @Html.ValidationMessageFor(model => model.tenkhachhang, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.diachi, new { htmlAttributes = new { @class = "form-control input-lg", @placeholder = "Địa Chỉ" } })
                            @Html.ValidationMessageFor(model => model.diachi, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.sdt, new { htmlAttributes = new { @class = "form-control input-lg", @placeholder = "số Điện Thoại" } })
                            @Html.ValidationMessageFor(model => model.sdt, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control input-lg", @placeholder = "Email" } })
                            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <hr class="colorgraph" />

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-default" />
                        </div>
                    </div>
                </div>
                }
            </div>
        </div>
    </div>
</section>



<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CUAHANGBANSACH/Views/GUESTLOGIN/UploadImage.cshtml
@model CUAHANGBANSACH.Models.KHACH

@{
    ViewBag.Title = "UploadImage";
}


<section id="content">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
                @using (Html.BeginForm("UploadImage", "GUESTLOGIN", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Upload ảnh cho khách @Model.makhachhang</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.makhachhang)

                        <div class="form-group">

                            <input type="file" class="form-control" name="image" />


                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Save" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }

                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>

            </div>
        </div>

    </div>

</section>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}