CUAHANGBANSACH/Controllers/QLNVController.cs
using CUAHANGBANSACH.Models;
using CUAHANGBANSACH.Models.Combined_Model;
using CUAHANGBANSACH.Models.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Web;
using System.Web.Mvc;

namespace CUAHANGBANSACH.Controllers
{
    public class QLNVController : Controller
    {
        // GET: QLNV
        public bool KiemTraPhanQuyen(string cv)
        {
            NHANVIEN nv = (NHANVIEN)Session["NhanVien"];
            var check = NHANVIEN_DAO.KiemTraPhanQuyen(nv.manhanvien, cv);
            if (check != null) return true;
            return false;
        }
        public ActionResult Index(string Find)
        {
            if (!KiemTraPhanQuyen("CV01")) return View("Bạn không có quyền vào đây");
            if (Find != null) return View(NHANVIEN_DAO.GetByName(Find));
            return View (NHANVIEN_DAO.GetAllList());
            
        }

        public ActionResult Details(string MaNV)
        {
            if (!KiemTraPhanQuyen("CV01")) return View("Bạn không có quyền vào đây");
            return View(NHANVIEN_DAO.GetById(MaNV));
        }

        public ActionResult Create (NHANVIEN_DANHSACHCHUCVU_MODEL model)
        {
            if (!KiemTraPhanQuyen("CV01")) return View("Bạn không có quyền vào đây");
            var laychucvu = CHUCVU_DAO.GetAllList();
            model.CHUCVU = laychucvu;
            return View(model);
        }

        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public ActionResult CreateNV  (NHANVIEN_DANHSACHCHUCVU_MODEL model)
        {
            var ttnv = NHANVIEN_DAO.GetByTen(model.NHANVIEN.tennhanvien);
            DateTime dt = new DateTime();
            if (ttnv == null)
            {
                dt = DateTime.Now;
                NHANVIEN nv = new NHANVIEN()
                {
                    manhanvien = "NV" + dt.ToString("yyyyMMddHHmmss"),
                    tennhanvien = model.NHANVIEN.tennhanvien,
                    tendangnhap = model.NHANVIEN.tendangnhap,
                    matkhau = model.NHANVIEN.matkhau
                };
                try
                {
                    NHANVIEN_DAO.Create(nv);
                    return RedirectToAction("Index");

                } catch
                {
                    return View("Lỗi thêm nhân viên");
                }
            }
            ModelState.AddModelError("tennhanvien", "Tên nhân viên đã tồn tại trong CSDL");
            return View(model);
        }
        public ActionResult Update (string MaNV)
        {
            if (!KiemTraPhanQuyen("CV01")) return View("Bạn không có quyền vào đây");
            var ttnv = NHANVIEN_DAO.GetById(MaNV);
            NHANVIEN_DANHSACHCHUCVU_MODEL model = new NHANVIEN_DANHSACHCHUCVU_MODEL()
            {
                NHANVIEN = ttnv,
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update (NHANVIEN_DANHSACHCHUCVU_MODEL model)
        {
            var ttnv = NHANVIEN_DAO.GetById(model.NHANVIEN.manhanvien);
            if (ttnv != null) {
                ttnv.tennhanvien = model.NHANVIEN.tennhanvien;
                ttnv.tendangnhap = model.NHANVIEN.tendangnhap;
                ttnv.matkhau = model.NHANVIEN.matkhau;

                try
                {
                    NHANVIEN_DAO.Update(ttnv);
                    return RedirectToAction("Index");

                } catch
                {
                    return View("Lỗi cập nhật thông tin");
                }
            }
            return View("Lỗi không tìm thấy nhân viên");
        }

        public ActionResult AddCV (string MaNV)
        {
            if (!KiemTraPhanQuyen("CV01")) return View("Bạn không có quyền vào đây");
            var ttnv = NHANVIEN_DAO.GetById2(MaNV);
            if (ttnv == null) return View("Lỗi không tìm thấy nhân viên");
            var dscv = CHUCVU_DAO.GetAllList();
            NHANVIEN_DANHSACHCHUCVU_MODEL model = new NHANVIEN_DANHSACHCHUCVU_MODEL()
            {
                NHANVIEN = ttnv,
                CHUCVU = dscv,
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddCV (NHANVIEN_DANHSACHCHUCVU_MODEL model)
        {
            string selectedCV = Request.Form["CHUCVU"];

            var ttnv = NHANVIEN_DAO.GetById2(model.NHANVIEN.manhanvien);
            if (ttnv == null) return View("Lỗi không tìm thấy nhân viên");

            var ktcv = CHITIETCHUCVU_DAO.FindCV(model.NHANVIEN.manhanvien, selectedCV);
            if (ktcv != null)
            {
                return View("Không thể thêm chức vụ");
            }
            DateTime dt = new DateTime();
            dt = DateTime.Now.AddYears(5);
            CHITIETCHUCVU ct = new CHITIETCHUCVU()
            {
                manhanvien = ttnv.manhanvien,
                machucvu = selectedCV,
                thoihanhopdong = dt,
            };

            try
            {
                CHITIETCHUCVU_DAO.Create(ct);
                return RedirectToAction("Index");
            } catch
            {
                return View("Có lỗi xảy ra");
            }
            //return View(model);
        }

        public ActionResult DeleteCV (string MaNV, string Ma_CV)
        {
            NHANVIEN login = (NHANVIEN)Session["NhanVien"];
            if (login.manhanvien == MaNV) return View("Không thể xóa chức vụ nhân viên đang đăng nhập");
            var ttnv = NHANVIEN_DAO.GetById2(MaNV);
            if (ttnv == null) return View("Lỗi không tìm thấy nhân viên");

            var ktcv = CHITIETCHUCVU_DAO.FindCV(MaNV, Ma_CV);
            if (ktcv == null)
            {
                return View("Không tìm thấy chức vụ");
            }

            try
            {
                CHITIETCHUCVU_DAO.Delete(ktcv); return RedirectToAction("Index");
            } catch
            {
                return View("Có lỗi xảy ra");
            }
        }

    }
}

CUAHANGBANSACH/Views/QLNV/AddCV.cshtml
@model CUAHANGBANSACH.Models.Combined_Model.NHANVIEN_DANHSACHCHUCVU_MODEL

@{
    ViewBag.Title = "AddCV";
    Layout = "~/Views/Shared/_Layout_Staff.cshtml";
}

<section id="content">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>THÊM CHỨC VỤ NHÂN VIÊN @Model.NHANVIEN.tennhanvien</h4>
                        <hr class="colorgraph" />
                        @Html.HiddenFor(model => model.NHANVIEN.manhanvien)
                        
                        <div class="form-group">

                            <div class="col-md-10">
                                <select name="CHUCVU" class="form-control">
                                    <option value="0">--Chọn Mã Nhân Viên</option>
                                    @foreach (var cv in Model.CHUCVU)
                                    {
                                        <option value="@cv.machucvu">@cv.tenchucvu</option>
                                    }
                                </select>
                            </div>
                        </div>



                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }

                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>

            </div>
        </div>

    </div>

</section>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CUAHANGBANSACH/Views/QLNV/Create.cshtml
@model CUAHANGBANSACH.Models.NHANVIEN

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout_Staff.cshtml";
}
}


<section id="content">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Thêm Nhân Viên</h4>

                        <h5>Tạo tài khoản</h5>
                        <hr class="colorgraph" />

                        <div class="form-group">

                            <div class="col-md-10">
                                @Html.EditorFor(model => model.tendangnhap, new { htmlAttributes = new { @class = "form-control input-lg", @placeholder = "Tên đăng nhập" } })
                                @Html.ValidationMessageFor(model => model.tendangnhap, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">

                            <div class="col-md-10">
                                @Html.EditorFor(model => model.matkhau, new { htmlAttributes = new { @class = "form-control input-lg", @placeholder = "Mật Khẩu", type = "password" } })
                                @Html.ValidationMessageFor(model => model.matkhau, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <hr class="colorgraph" />
                        <h5>Thông tin nhân viên cơ bản</h5>

                        <div class="form-group">

                            <div class="col-md-10">
                                @Html.EditorFor(model => model.tennhanvien, new { htmlAttributes = new { @class = "form-control input-lg", @placeholder = "Tên Nhân Viên" } })
                                @Html.ValidationMessageFor(model => model.tennhanvien, "", new { @class = "text-danger" })
                            </div>
                        </div>


                        <div class="form-group">

                            <div class="col-md-10">
                                @Html.DropDownList("SelectedChucVu", ViewBag.CHUCVU as SelectList, "Chọn Chức vụ", new { @class = "form-control" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }

                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>

            </div>
        </div>

    </div>
</section>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CUAHANGBANSACH/Views/QLNV/Details.cshtml
@model CUAHANGBANSACH.Models.NHANVIEN

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout_Staff.cshtml";
}


<section id="content">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h4>CHI TIẾT NHÂN VIÊN @Model.manhanvien</h4>
                <hr class="colorgraph" />

                <dl class="dl-horizontal">

                    <dt>
                        @Html.DisplayNameFor(model => model.tennhanvien)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.tennhanvien)
                    </dd>

                </dl>
            </div>

            <hr class="colorgraph" />
            <div class="col-lg-12">
       
                <h4>Danh sách chức vụ mà nhân viện @Model.manhanvien hiện đang làm </h4>
                <hr  class="colorgraph"/>

                <p>
                    <input type="button" style="color: white; background-color: darkblue;" value="Thêm chức vụ" onclick="location.href='@Url.Action("AddCV", "QLNV", routeValues: new { @MaNV = Model.manhanvien })'" />
                    
                </p>
                <table class="table">
                    <tr>
                        <th>Tên Chức Vụ</th>

                        <th></th>
                    </tr>

                    @foreach (var item in Model.chucvu)
                    {
                        @Html.HiddenFor(model => item.machucvu)
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.tenchucvu)
                            </td>

                            <td>
                               
                                <input type="button" style="color: white; background-color: red;" value="Xóa chức vụ" onclick="location.href='@Url.Action("DeleteCV", "QLNV", routeValues: new { @MaNV = Model.manhanvien, @Ma_CV = item.machucvu })'" />
                            </td>
                        </tr>
                    }
                </table>
                <p>

                    @Html.ActionLink("Back to List", "Index")
                </p>
            </div>
        </div>
    </div>

</section>

CUAHANGBANSACH/Views/QLNV/Index.cshtml
@model IEnumerable<CUAHANGBANSACH.Models.NHANVIEN>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_Staff.cshtml";
}


<section id="content">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2>DANH SÁCH TÀI KHOẢN NHÂN VIÊN</h2>
                <hr class="colorgraph" />
                <div class="col-lg-4" style="margin-top:10px; margin-bottom: 10px">
                    <input type="button" style="color: white; background-color: yellowgreen;" value="Thêm nhân viên" onclick="location.href='@Url.Action("Create", "QLNV")'" />

                </div>

                <div class="col-lg-8" style="margin-top:10px; margin-bottom: 10px">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        <div class="col-lg-6">

                            @Html.Editor("Find", "", new { htmlAttributes = new { @class = "form-control input-lg", @placeholder = "Nhập tên nhân viên cần tìm" } })

                        </div>
                        <div class="col-lg-2">
                            <input type="submit" value="Tìm kiếm" class="btn btn-default" />
                        </div>
                    }
                </div>
               
                <table class="table">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.manhanvien)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.tendangnhap)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.tennhanvien)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.matkhau)
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.manhanvien)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.tendangnhap)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.tennhanvien)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.matkhau)
                            </td>
                            <td>
                                <input type="button" style="color: white; background-color:darkblue;" value="Edit" onclick="location.href='@Url.Action("Update", "QLNV", routeValues: new { @MaNV = item.manhanvien })'" />
                                <input type="button" style="color: white; background-color: red;" value="Thông tin nhân viên" onclick="location.href='@Url.Action("Details","QLNV", routeValues: new { @MaNV = item.manhanvien })'" />
                                <input type="button" style="color: white; background-color: grey;" value="Xóa nhân viên" onclick="location.href='@Url.Action("Delete","QLNV", routeValues: new { @MaNV = item.manhanvien })'" />

                            </td>
                        </tr>
                    }

                </table>
            </div>
        </div>
    </div>

    
</section>

CUAHANGBANSACH/Views/QLNV/Update.cshtml
@model CUAHANGBANSACH.Models.Combined_Model.NHANVIEN_DANHSACHCHUCVU_MODEL

@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Layout_Staff.cshtml";
}

<section id="content">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Cập nhật thông tin nhân viên @Model.NHANVIEN.tennhanvien</h4>
                        @Html.HiddenFor(model => model.NHANVIEN.manhanvien)

                        <h5>Cập nhật tài khoản</h5>
                        <hr class="colorgraph" />

                        <div class="form-group">

                            <div class="col-md-10">
                                @Html.EditorFor(model => model.NHANVIEN.tendangnhap, new { htmlAttributes = new { @class = "form-control input-lg", @placeholder = "Tên đăng nhập" } })
                                @Html.ValidationMessageFor(model => model.NHANVIEN.tendangnhap, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">

                            <div class="col-md-10">
                                @Html.EditorFor(model => model.NHANVIEN.matkhau, new { htmlAttributes = new { @class = "form-control input-lg", @placeholder = "Mật Khẩu", type = "password" } })
                                @Html.ValidationMessageFor(model => model.NHANVIEN.matkhau, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <hr class="colorgraph" />
                        <h5>Cập nhật Thông tin nhân viên cơ bản</h5>

                        <div class="form-group">

                            <div class="col-md-10">
                                @Html.EditorFor(model => model.NHANVIEN.tennhanvien, new { htmlAttributes = new { @class = "form-control input-lg", @placeholder = "Tên Nhân Viên" } })
                                @Html.ValidationMessageFor(model => model.NHANVIEN.tennhanvien, "", new { @class = "text-danger" })
                            </div>
                        </div>


                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }

                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>

            </div>
        </div>

    </div>
</section>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}